version: "3"

services:
  app:
    build: "."
    env_file: ".env"
    ports:
      - "8300:8300"
    depends_on:
      - redisdb
    links:
      - redisdb:redisdb

  redisdb:
    image: redis
    ports:
      - 6379:6379
